force-app/main/default/objects/Feature_Flag__mdt/Feature_Flag__mdt.object-meta.xml
<CustomObject>
    <label>Feature Flag</label>
    <pluralLabel>Feature Flags</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Flag__mdt/fields/Flag_Value__c.field-meta.xml
<CustomField>
    <fullName>Flag_Value__c</fullName>
    <label>Flag Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feature_Flag__mdt/fields/isEnabled__c.field-meta.xml
<CustomField>
    <fullName>isEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this feature is enabled</description>
    <label>isEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feature_Flag_Enabled_For__mdt/Feature_Flag_Enabled_For__mdt.object-meta.xml
<CustomObject>
    <label>Feature Flag Enabled For</label>
    <pluralLabel>Feature Flags Enabled For</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Flag_Enabled_For__mdt/fields/Feature_Flag__c.field-meta.xml
<CustomField>
    <fullName>Feature_Flag__c</fullName>
    <label>Feature Flag</label>
    <referenceTo>Feature_Flag__mdt</referenceTo>
    <relationshipLabel>Feature Flags Enabled For</relationshipLabel>
    <relationshipName>Feature_Flags_Enabled_For</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Feature_Flag_Enabled_For__mdt/fields/isEnabled__c.field-meta.xml
<CustomField>
    <fullName>isEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feature_Flag_Enabled_For__mdt/fields/Permission_Set_Id__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Id__c</fullName>
    <label>Permission Set Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/feature flags/FeatureFlagCommonTests.cls
/**
 * @description Class serves to DRY code for various testing methods that
 * require it.
 */
@isTest
public class FeatureFlagCommonTests {
    public static Map<String, Feature_Flag__mdt> getTestFlag(
        String flagName,
        Boolean enabled
    ) {
        Map<String, Feature_Flag__mdt> testFlag = new Map<String, Feature_Flag__mdt>();
        testFlag.put(
            'TestFlag',
            new Feature_Flag__mdt(
                Label = flagName,
                DeveloperName = flagName,
                id = 'm021h000000lDU8',
                isEnabled__c = enabled,
                flag_value__c = 'test value'
            )
        );
        return testFlag;
    }

    public static Id getExistingPermSetId() {
        return new SOQL.Builder('PermissionSet')
            .selectField('Id')
            .build()
            .getRecord()
            .Id;
    }

    public static Map<String, Feature_Flag_Enabled_For__mdt> getOverriddenPerPermSet(
        String flagName,
        Id permSetId,
        Boolean enabled
    ) {
        Map<String, Feature_Flag_Enabled_For__mdt> overriddenPerPermSet = new Map<String, Feature_Flag_Enabled_For__mdt>();
        overriddenPerPermSet.put(
            flagName,
            new Feature_Flag_Enabled_For__mdt(
                Label = 'TestFlag',
                DeveloperName = 'TestFlag',
                Feature_Flag__c = 'm021h000000lDU8',
                isEnabled__c = enabled,
                Permission_Set_Id__c = permSetId
            )
        );
        return overriddenPerPermSet;
    }
}